version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.7.9-alpine"
    expose:
      - 5672
  producer:
    build: ./producer
    environment:
      - RabbitURL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  consumer:
    build: ./consumer
    environment:
      - RabbitURL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
